name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore App.Prueba.sln

      # 4. Build project
      - name: Build project
        run: dotnet build App.Prueba.sln --configuration Release --no-restore

      # 5. Publish app
      - name: Publish app
        run: dotnet publish App.Prueba/App.Prueba.csproj --configuration Release --output ./published

      # 6. Deploy to IIS using WinRM
      - name: Deploy to IIS
        run: |
          $server = "t3-dev-iis.teee3.com"
          $username = "jose.maria@teee3.com"
          $password = ConvertTo-SecureString "Clave3.Gambit$!" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $password)

          Invoke-Command -ComputerName $server -Credential $credential -ScriptBlock {
            param ($source, $destination)
            # Copiar los archivos publicados al servidor IIS
            Copy-Item -Path $source -Destination $destination -Recurse -Force
          } -ArgumentList "$(pwd)/published", "C:\inetpub\wwwroot\App.Prueba"
