name: Deploy to IIS via SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configuración de .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    # 3. Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore App.Prueba/App.Prueba.sln

    # 4. Compilar proyecto
    - name: Build project
      run: dotnet build App.Prueba/App.Prueba.sln --configuration Release --no-restore

    # 5. Publicar aplicación
    - name: Publish app
      run: dotnet publish App.Prueba/Api.Prueba/Api.Prueba.csproj --configuration Release --output ./published

    # 6. Desplegar en IIS usando SSH
    - name: Deploy to IIS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: "10.90.102.202"
        username: "jose.maria@teee3.com"
        password: "Clave3.Gambit$!"
        port: 22
        script: |
          mkdir -p "C:\App.Prueba"
          xcopy /S /E /Y "./published" "C:\App.Prueba"

    # 7. Reiniciar el sitio en IIS
    - name: Restart IIS Site
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: "10.90.102.202"
        username: "jose.maria@teee3.com"
        password: "Clave3.Gambit$!"
        port: 22
        script: |
          Import-Module WebAdministration
          Restart-WebAppPool -Name "Api.Prueba"

    # 8. Limpieza (opcional)
    - name: Cleanup
      run: Remove-Item -Path ./published -Recurse -Force
