name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # 1. Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configuración de .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    # 3. Restaurar dependencias
    - name: Restore dependencies
      run: dotnet restore App.Prueba/App.Prueba.sln

    # 4. Compilar proyecto
    - name: Build project
      run: dotnet build App.Prueba/App.Prueba.sln --configuration Release --no-restore

    # 5. Publicar aplicación
    - name: Publish app
      run: dotnet publish App.Prueba/App.Prueba.csproj --configuration Release --output ./published

    # 6. Desplegar en IIS
    - name: Deploy to IIS
      run: |
        $server = "t3-dev-iis.teee3.com"
        $username = "jose.maria@teee3.com"
        $password = ConvertTo-SecureString "Clave3.Gambit$!" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $password)
        Invoke-Command -ComputerName $server -Credential $credential -ScriptBlock {
          New-Item -Path "C:\inetpub\wwwroot\App.Prueba" -ItemType Directory -Force
          Copy-Item -Path "./published/*" -Destination "C:\inetpub\wwwroot\App.Prueba" -Recurse -Force
        }
