name: Deploy to IIS

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuración de .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0  # Cambia según tu versión de .NET

      # 3. Publicar la aplicación
      - name: Publish app
        run: |
          dotnet publish App.Prueba/Api.Prueba/Api.Prueba.csproj -c Release -o published

      # 4. Desplegar a IIS usando PowerShell
      - name: Deploy to IIS
        shell: pwsh
        run: |
          $username = "${{ secrets.IIS_USER }}"
          $password = ConvertTo-SecureString "${{ secrets.IIS_PASS }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $password)

          # Establecer conexión remota
          Invoke-Command -ComputerName ${{ secrets.IIS_HOST }} -Credential $credential -ScriptBlock {
            param($source, $target)
            
            # Crear el directorio de destino si no existe
            if (-Not (Test-Path -Path $target)) {
              New-Item -ItemType Directory -Force -Path $target
            }

            # Copiar archivos
            Copy-Item -Path $source/* -Destination $target -Recurse -Force
          } -ArgumentList "$(pwd)/published", "C:/App.Prueba/"
