name: Deploy to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # 1. Checkout del c贸digo fuente
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configuraci贸n de .NET Core
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' # Cambia a la versi贸n de .NET que uses

    # 3. Restaurar dependencias y compilar
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    # 4. Publicar la aplicaci贸n
    - name: Publish app
      run: dotnet publish -c Release -o published

    # 5. Desplegar a IIS
    - name: Deploy to IIS
      run: |
        $username = "${{ secrets.IIS_USER }}"
        $password = ConvertTo-SecureString "${{ secrets.IIS_PASS }}" -AsPlainText -Force
        $server = "${{ secrets.IIS_HOST }}"
        $credential = New-Object System.Management.Automation.PSCredential ($username, $password)
        Invoke-Command -ComputerName $server -Credential $credential -ScriptBlock {
            # Copiar los archivos publicados al directorio del sitio IIS
            Copy-Item -Path "${{ github.workspace }}\published\*" -Destination "C:\inetpub\wwwroot\App.Prueba" -Recurse -Force
        }

    # (Opcional) Limpiar los artefactos temporales
    - name: Cleanup
      run: Remove-Item -Recurse -Force published
